### ISSUE TITLE
Need code/script to parse the library.bib into primary.bib

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/privacy-bibliography#19]

**Comment by ianschmutte** [comment]
@larsvilhuber, can you elaborate on this task?

**Comment by larsvilhuber** [comment]
How do you get from "library.bib" into "primary.bib" using parsing on keyword "primary"? Need a script (could we treat "primary.bib" as transient, built from within _build.sh?)

**Comment by ianschmutte** [comment]
I see.. At first, I hand-labeled all entries in library.bib with keyword tags. The original intent was to use these with biblatex to automate separate sub-reference lists based on the full library.bib

Once we switched to bookdown, I extracted primary.bib manually with a jabref keyword search. 

I can figure out how to script it. Just to confirm, moving forward, the idea is that
* new entries are added directly to library.bib with appropriate keyword tags
* The script extracts primary.bib before doing the new bookdown compile

**Comment by larsvilhuber** [comment]
Yup.

--
Lars Vilhuber
on mobile device

________________________________

**Comment by larsvilhuber** [comment]
You might read into r, then write out again.

--
Lars Vilhuber
on mobile device

________________________________

**Comment by larsvilhuber** [comment]
Knitcitations or refmanager both have ability to read and write.
________________________________

**Comment by ianschmutte** [comment]
RefManageR will work great. However, on importing library.bib it finds (unsurprisingly) a lot of errors. It will take a little more attention than I have right now to decide how to manage errors in an elegant manner

**Comment by larsvilhuber** [comment]
Errors that affect the primary ones? All you need is to strip them out.

--
Lars Vilhuber
on mobile device

________________________________

**Comment by ianschmutte** [comment]
* I've fixed library.bib so that compilation of index.Rmd based on primary.bib generated using RefManageR. Specifically, I eliminated the inconsistencies identified below.

* Next step is for Lars to build in automated generation of primary.bib as part of the _deploy.sh

## Email communication from @larsvilhuber 

`Well, as long as you can disambiguate what is different in the common entries, and which entries are not present... 

I found 64 filtering library.bib on primary (at least using RefManageR), and 73 entries in primary.bib

> primary.old.bib <- RefManageR::ReadBib("primary-manual.bib")
Ignoring entry 'Varian1998'  (line1029) because:
A bibentry of bibtype ‘TechReport’ has to specify the field: institution
> nrow(summary(primary.old.bib))
[1] 71
> nrow(summary(primary.bib))
[1] 64

Records in automatic, not in manual:

> anti_join(primary.ds,primary.old.ds,by=c("key"))$key
[1] "abowd:schmutte:BPEA:2015" "Dworketal:JPC:2017"       "Varian1998"               "Campbell:Privacy:JEMS:"  

Records in manual, not in automatic:

> anti_join(primary.old.ds,primary.ds,by=c("key"))$key
 [1] "abowdschmutteBPEA2015"             "Campbell:Privacy:JEMS"             "title13"                          
 [4] "cipsea2002"                        "cipsea"                            "Dwork:Roth:journal:version:2014"  
 [7] "jones:2017"                        "Harvard:DataPrivacyLab"            "Harvard:PrivacyTools"             
[10] "Nissim:DPNonTech:WP:2018"          "PomattoTheCostOfInformation2018:1"

You can also run anti_join on all variables (drop the by statement) to get all records that are NOT identical.

See diagnostics.R in the latest commit.

Just modify in master, or branch-and-pull, as you wish.`
